language: php
php:
  - "5.4"

before_script:
  - psql -U postgres -c "CREATE EXTENSION postgis"
  - psql -U postgres -c "CREATE USER gisclient PASSWORD 'gsiclient' SUPERUSER"
  - psql -U postgres -c "CREATE DATABASE gisclient_ci OWNER gisclient TEMPLATE postgis;" 
  - cp config/travis/config.php travis/config.php
  - cp config/travis/config.db.php travis/config.db.php
  - php config/installer.php
